// <auto-generated />
using System;
using AktuelUrunBulucu.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AktuelUrunBulucu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317210250_AddNotificationRequest")]
    partial class AddNotificationRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AktuelUrunBulucu.DAL.Entities.NotificationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("SearchedProduct")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("searched_product");

                    b.HasKey("Id");

                    b.ToTable("notification_requests", "public");
                });

            modelBuilder.Entity("AktuelUrunBulucu.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("ProductBringDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("product_bring_date");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("store_name");

                    b.HasKey("Id");

                    b.ToTable("products", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Beyaz Eşya",
                            Name = "Çamaşır Makinesi Samsung 8kg",
                            ProductBringDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Beyaz Eşya",
                            Name = "Bulaşık Makinesi Arçelik 5 Program",
                            ProductBringDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Beyaz Eşya",
                            Name = "Buzdolabı Vestel No-Frost",
                            ProductBringDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Küçük Ev Aleti",
                            Name = "Mikrodalga Fırın 20L",
                            ProductBringDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Küçük Ev Aleti",
                            Name = "Elektrikli Süpürge Rowenta",
                            ProductBringDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Küçük Ev Aleti",
                            Name = "Hava Fritözü 5L",
                            ProductBringDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Spor & Outdoor",
                            Name = "Bisiklet 26 Jant Dağ Bisikleti",
                            ProductBringDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Spor & Outdoor",
                            Name = "Bisiklet Çocuk 20 Jant",
                            ProductBringDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Kamp & Outdoor",
                            Name = "Çadır 4 Kişilik Kamp Çadırı",
                            ProductBringDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Kamp & Outdoor",
                            Name = "Çadır 2 Kişilik Ultra Hafif",
                            ProductBringDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Bahçe & Piknik",
                            Name = "Barbekü Izgara Kömürlü Set",
                            ProductBringDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Bahçe & Piknik",
                            Name = "Barbekü Izgara Gazlı Taşınabilir",
                            ProductBringDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Bahçe & Piknik",
                            Name = "Bahçe Hortumu 25m",
                            ProductBringDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Bahçe & Piknik",
                            Name = "Çim Biçme Makinesi Elektrikli",
                            ProductBringDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Mobilya & Dekorasyon",
                            Name = "Bahçe Masa Sandalye Seti 4+1",
                            ProductBringDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Kamp & Outdoor",
                            Name = "Katlanır Kamp Sandalyesi",
                            ProductBringDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Mobilya & Dekorasyon",
                            Name = "Raf Sistemi Metal 5 Katlı",
                            ProductBringDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Kamp & Outdoor",
                            Name = "Uyku Tulumu -5 Derece",
                            ProductBringDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Giyim",
                            Name = "Yağmurluk Unisex L Beden",
                            ProductBringDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Giyim",
                            Name = "Spor Ayakkabı Erkek 42",
                            ProductBringDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Elektronik",
                            Name = "Akıllı Saat Fitness Tracker",
                            ProductBringDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Elektronik",
                            Name = "Bluetooth Hoparlör Su Geçirmez",
                            ProductBringDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Elektronik",
                            Name = "Powerbank 20000mAh",
                            ProductBringDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Çocuk & Oyuncak",
                            Name = "Çocuk Scooter 3 Tekerlekli",
                            ProductBringDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Çocuk & Oyuncak",
                            Name = "Kaydırak Çocuk Bahçe Seti",
                            ProductBringDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Araç Gereç",
                            Name = "Matkap Seti Akülü 18V",
                            ProductBringDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Bahçe & Piknik",
                            Name = "El Arabası Plastik Bahçe",
                            ProductBringDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Araç Gereç",
                            Name = "Merdiven 5 Basamak Alüminyum",
                            ProductBringDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Yaz & Havuz",
                            Name = "Şişme Havuz 300x200cm Aile",
                            ProductBringDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Yaz & Havuz",
                            Name = "Güneş Şemsiyesi 2m UV Korumalı",
                            ProductBringDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        });
                });

            modelBuilder.Entity("AktuelUrunBulucu.DAL.Entities.SearchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("searched_at");

                    b.Property<string>("SearchedProduct")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("searched_product");

                    b.HasKey("Id");

                    b.ToTable("search_logs", "public");
                });

            modelBuilder.Entity("AktuelUrunBulucu.DAL.Entities.UserCoordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.HasKey("Id");

                    b.ToTable("user_coordinates", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
