// <auto-generated />
using System;
using AktuelUrunBulucu.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AktuelUrunBulucu.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618082949_AddAllTablesSeedData")]
    partial class AddAllTablesSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AktuelUrunBulucu.DAL.Entities.NotificationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("SearchedProduct")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("searched_product");

                    b.HasKey("Id");

                    b.ToTable("notification_requests", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmet.yilmaz@gmail.com",
                            IpAddress = "85.102.45.12",
                            RequestedAt = new DateTime(2026, 6, 10, 9, 16, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "mangal"
                        },
                        new
                        {
                            Id = 2,
                            Email = "elif.demir@hotmail.com",
                            IpAddress = "78.160.32.88",
                            RequestedAt = new DateTime(2026, 6, 10, 10, 32, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "powerbank 30000"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mehmet.kaya@outlook.com",
                            IpAddress = "176.42.115.200",
                            RequestedAt = new DateTime(2026, 6, 11, 14, 50, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "çamaşır makinesi"
                        },
                        new
                        {
                            Id = 4,
                            Email = "zeynep.celik@gmail.com",
                            IpAddress = "31.223.78.55",
                            RequestedAt = new DateTime(2026, 6, 12, 8, 5, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "hava fritözü"
                        },
                        new
                        {
                            Id = 5,
                            Email = "can.ozturk@yandex.com",
                            IpAddress = "95.70.130.44",
                            RequestedAt = new DateTime(2026, 6, 12, 11, 15, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "çadır 4 kişilik"
                        },
                        new
                        {
                            Id = 6,
                            Email = "ayse.sahin@gmail.com",
                            IpAddress = "212.174.60.33",
                            RequestedAt = new DateTime(2026, 6, 14, 9, 42, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "güneş kremi"
                        },
                        new
                        {
                            Id = 7,
                            Email = "ahmet.yilmaz@gmail.com",
                            IpAddress = "85.102.45.12",
                            RequestedAt = new DateTime(2026, 6, 15, 17, 35, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "kulaklık bluetooth"
                        },
                        new
                        {
                            Id = 8,
                            Email = "elif.demir@hotmail.com",
                            IpAddress = "78.160.32.88",
                            RequestedAt = new DateTime(2026, 6, 16, 14, 5, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "akıllı saat"
                        },
                        new
                        {
                            Id = 9,
                            Email = "mehmet.kaya@outlook.com",
                            IpAddress = "176.42.115.200",
                            RequestedAt = new DateTime(2026, 6, 17, 11, 25, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "robot süpürge"
                        },
                        new
                        {
                            Id = 10,
                            Email = "zeynep.celik@gmail.com",
                            IpAddress = "31.223.78.55",
                            RequestedAt = new DateTime(2026, 6, 17, 15, 40, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "bisiklet çocuk"
                        });
                });

            modelBuilder.Entity("AktuelUrunBulucu.DAL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("ProductBringDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("product_bring_date");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("store_name");

                    b.HasKey("Id");

                    b.ToTable("products", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Beyaz Eşya",
                            Name = "Çamaşır Makinesi Samsung 8kg",
                            ProductBringDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Beyaz Eşya",
                            Name = "Bulaşık Makinesi Arçelik 5 Program",
                            ProductBringDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Beyaz Eşya",
                            Name = "Buzdolabı Vestel No-Frost",
                            ProductBringDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Küçük Ev Aleti",
                            Name = "Mikrodalga Fırın 20L",
                            ProductBringDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Küçük Ev Aleti",
                            Name = "Elektrikli Süpürge Rowenta",
                            ProductBringDate = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Küçük Ev Aleti",
                            Name = "Hava Fritözü 5L",
                            ProductBringDate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Spor & Outdoor",
                            Name = "Bisiklet 26 Jant Dağ Bisikleti",
                            ProductBringDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Spor & Outdoor",
                            Name = "Bisiklet Çocuk 20 Jant",
                            ProductBringDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Kamp & Outdoor",
                            Name = "Çadır 4 Kişilik Kamp Çadırı",
                            ProductBringDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Kamp & Outdoor",
                            Name = "Çadır 2 Kişilik Ultra Hafif",
                            ProductBringDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Bahçe & Piknik",
                            Name = "Barbekü Izgara Kömürlü Set",
                            ProductBringDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Bahçe & Piknik",
                            Name = "Barbekü Izgara Gazlı Taşınabilir",
                            ProductBringDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Bahçe & Piknik",
                            Name = "Bahçe Hortumu 25m",
                            ProductBringDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Bahçe & Piknik",
                            Name = "Çim Biçme Makinesi Elektrikli",
                            ProductBringDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Mobilya & Dekorasyon",
                            Name = "Bahçe Masa Sandalye Seti 4+1",
                            ProductBringDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Kamp & Outdoor",
                            Name = "Katlanır Kamp Sandalyesi",
                            ProductBringDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Mobilya & Dekorasyon",
                            Name = "Raf Sistemi Metal 5 Katlı",
                            ProductBringDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Kamp & Outdoor",
                            Name = "Uyku Tulumu -5 Derece",
                            ProductBringDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Giyim",
                            Name = "Yağmurluk Unisex L Beden",
                            ProductBringDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Giyim",
                            Name = "Spor Ayakkabı Erkek 42",
                            ProductBringDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Elektronik",
                            Name = "Akıllı Saat Fitness Tracker",
                            ProductBringDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Elektronik",
                            Name = "Bluetooth Hoparlör Su Geçirmez",
                            ProductBringDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Elektronik",
                            Name = "Powerbank 20000mAh",
                            ProductBringDate = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Çocuk & Oyuncak",
                            Name = "Çocuk Scooter 3 Tekerlekli",
                            ProductBringDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Çocuk & Oyuncak",
                            Name = "Kaydırak Çocuk Bahçe Seti",
                            ProductBringDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Araç Gereç",
                            Name = "Matkap Seti Akülü 18V",
                            ProductBringDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Bahçe & Piknik",
                            Name = "El Arabası Plastik Bahçe",
                            ProductBringDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Araç Gereç",
                            Name = "Merdiven 5 Basamak Alüminyum",
                            ProductBringDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Yaz & Havuz",
                            Name = "Şişme Havuz 300x200cm Aile",
                            ProductBringDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Yaz & Havuz",
                            Name = "Güneş Şemsiyesi 2m UV Korumalı",
                            ProductBringDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Kömürlü Set Takım Çantalı",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Büyük Boy Aile Mangalı",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Portatif Katlanır Kamp Mangalı",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Gazlı Taşınabilir 2 Gözlü",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Elektrikli İç Mekan 2000W",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Kömürü 5kg Doğal Meyve Odunu",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Kömürü 10kg Premium",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Ateş Tutuşturucu Jel 500ml",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Izgara Teli 40x60cm Paslanmaz",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Maşa Spatula Set 5 Parça",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Eldiveni Isıya Dayanıklı Çift",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Izgarası Döküm Demir 50cm",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Barbekü Sis Şişi 12li Set",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Alüminyum Folyo Tepsi 5li",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Bahçe & Piknik",
                            Name = "Mangal Çantalı Piknik Seti 20 Parça",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Elektronik",
                            Name = "Powerbank 5000mAh Slim Taşınabilir",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Elektronik",
                            Name = "Powerbank 10000mAh Hızlı Şarj 22.5W",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Elektronik",
                            Name = "Powerbank 20000mAh Çift USB Çıkış",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Elektronik",
                            Name = "Powerbank 20000mAh PD 65W Laptop",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Elektronik",
                            Name = "Powerbank 30000mAh Süper Kapasite",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Elektronik",
                            Name = "Powerbank Kablosuz Şarjlı 15W MagSafe",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Elektronik",
                            Name = "Powerbank Solar Güneş Enerjili 10000mAh",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Elektronik",
                            Name = "Powerbank Mini Anahtarlık 1500mAh",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Elektronik",
                            Name = "Powerbank 10000mAh Led Göstergeli",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Elektronik",
                            Name = "Powerbank 25000mAh 4 Portlu Hızlı Şarj",
                            ProductBringDate = new DateTime(2026, 4, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Gıda",
                            Name = "Zeytinyağı Riviera 5L Teneke",
                            ProductBringDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Gıda",
                            Name = "Fındık İç 1kg Giresun",
                            ProductBringDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Gıda",
                            Name = "Bal Süzme Çam Balı 850g",
                            ProductBringDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Gıda",
                            Name = "Çay Rize Çayı 3kg Karton Kutu",
                            ProductBringDate = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Gıda",
                            Name = "Türk Kahvesi 500g Öğütülmüş",
                            ProductBringDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Kozmetik",
                            Name = "Güneş Kremi SPF50 200ml",
                            ProductBringDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Kozmetik",
                            Name = "Saç Kurutma Makinesi 2200W İyonik",
                            ProductBringDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 63,
                            Category = "Kozmetik",
                            Name = "Epilatör Su Geçirmez Şarjlı",
                            ProductBringDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Kozmetik",
                            Name = "Parfüm Erkek EDT 100ml",
                            ProductBringDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Ev Tekstili",
                            Name = "Nevresim Takımı Çift Kişilik Pamuk",
                            ProductBringDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Ev Tekstili",
                            Name = "Havlu Seti 6lı Banyo Havlusu",
                            ProductBringDate = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Ev Tekstili",
                            Name = "Yastık Visco Ortopedik Boyun",
                            ProductBringDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Temizlik",
                            Name = "Çamaşır Deterjanı 10kg Toz",
                            ProductBringDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Temizlik",
                            Name = "Bulaşık Deterjanı Tablet 72li",
                            ProductBringDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Küçük Ev Aleti",
                            Name = "Robot Süpürge Akıllı Lazerli",
                            ProductBringDate = new DateTime(2026, 6, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Otomotiv",
                            Name = "Araç İçi Telefon Tutucu Manyetik",
                            ProductBringDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "A101"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Otomotiv",
                            Name = "Araç Kompresörü 12V Dijital",
                            ProductBringDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "BİM"
                        },
                        new
                        {
                            Id = 73,
                            Category = "Otomotiv",
                            Name = "Araç Koltuk Kılıfı Deri Universal",
                            ProductBringDate = new DateTime(2026, 6, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Şok"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Elektronik",
                            Name = "Tablet Kalem Stylus iPad Uyumlu",
                            ProductBringDate = new DateTime(2026, 6, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "Migros"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Elektronik",
                            Name = "Kulaklık Bluetooth ANC Gürültü Önleyici",
                            ProductBringDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            StoreName = "CarrefourSA"
                        });
                });

            modelBuilder.Entity("AktuelUrunBulucu.DAL.Entities.SearchLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("SearchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("searched_at");

                    b.Property<string>("SearchedProduct")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("searched_product");

                    b.HasKey("Id");

                    b.ToTable("search_logs", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IpAddress = "85.102.45.12",
                            SearchedAt = new DateTime(2026, 6, 10, 9, 15, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "mangal"
                        },
                        new
                        {
                            Id = 2,
                            IpAddress = "78.160.32.88",
                            SearchedAt = new DateTime(2026, 6, 10, 10, 30, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "powerbank"
                        },
                        new
                        {
                            Id = 3,
                            IpAddress = "176.42.115.200",
                            SearchedAt = new DateTime(2026, 6, 11, 14, 45, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "çamaşır makinesi"
                        },
                        new
                        {
                            Id = 4,
                            IpAddress = "85.102.45.12",
                            SearchedAt = new DateTime(2026, 6, 11, 16, 20, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "bisiklet"
                        },
                        new
                        {
                            Id = 5,
                            IpAddress = "31.223.78.55",
                            SearchedAt = new DateTime(2026, 6, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "hava fritözü"
                        },
                        new
                        {
                            Id = 6,
                            IpAddress = "95.70.130.44",
                            SearchedAt = new DateTime(2026, 6, 12, 11, 10, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "çadır"
                        },
                        new
                        {
                            Id = 7,
                            IpAddress = "78.160.32.88",
                            SearchedAt = new DateTime(2026, 6, 13, 13, 25, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "bluetooth hoparlör"
                        },
                        new
                        {
                            Id = 8,
                            IpAddress = "176.42.115.200",
                            SearchedAt = new DateTime(2026, 6, 13, 15, 55, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "buzdolabı"
                        },
                        new
                        {
                            Id = 9,
                            IpAddress = "212.174.60.33",
                            SearchedAt = new DateTime(2026, 6, 14, 9, 40, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "güneş kremi"
                        },
                        new
                        {
                            Id = 10,
                            IpAddress = "31.223.78.55",
                            SearchedAt = new DateTime(2026, 6, 14, 12, 15, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "zeytinyağı"
                        },
                        new
                        {
                            Id = 11,
                            IpAddress = "95.70.130.44",
                            SearchedAt = new DateTime(2026, 6, 15, 10, 5, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "robot süpürge"
                        },
                        new
                        {
                            Id = 12,
                            IpAddress = "85.102.45.12",
                            SearchedAt = new DateTime(2026, 6, 15, 17, 30, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "kulaklık"
                        },
                        new
                        {
                            Id = 13,
                            IpAddress = "212.174.60.33",
                            SearchedAt = new DateTime(2026, 6, 16, 8, 50, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "nevresim"
                        },
                        new
                        {
                            Id = 14,
                            IpAddress = "78.160.32.88",
                            SearchedAt = new DateTime(2026, 6, 16, 14, 0, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "akıllı saat"
                        },
                        new
                        {
                            Id = 15,
                            IpAddress = "176.42.115.200",
                            SearchedAt = new DateTime(2026, 6, 17, 11, 20, 0, 0, DateTimeKind.Utc),
                            SearchedProduct = "deterjan"
                        });
                });

            modelBuilder.Entity("AktuelUrunBulucu.DAL.Entities.UserCoordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.HasKey("Id");

                    b.ToTable("user_coordinates", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IpAddress = "85.102.45.12",
                            Latitude = 41.008200000000002,
                            Longitude = 28.978400000000001,
                            SavedAt = new DateTime(2026, 6, 10, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            IpAddress = "78.160.32.88",
                            Latitude = 39.933399999999999,
                            Longitude = 32.859699999999997,
                            SavedAt = new DateTime(2026, 6, 10, 10, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            IpAddress = "176.42.115.200",
                            Latitude = 38.419199999999996,
                            Longitude = 27.128699999999998,
                            SavedAt = new DateTime(2026, 6, 11, 14, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            IpAddress = "31.223.78.55",
                            Latitude = 37.0,
                            Longitude = 35.321300000000001,
                            SavedAt = new DateTime(2026, 6, 12, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            IpAddress = "95.70.130.44",
                            Latitude = 36.896900000000002,
                            Longitude = 30.7133,
                            SavedAt = new DateTime(2026, 6, 12, 11, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            IpAddress = "212.174.60.33",
                            Latitude = 40.188499999999998,
                            Longitude = 29.061,
                            SavedAt = new DateTime(2026, 6, 14, 9, 40, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            IpAddress = "85.102.45.12",
                            Latitude = 41.008200000000002,
                            Longitude = 28.978400000000001,
                            SavedAt = new DateTime(2026, 6, 15, 17, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            IpAddress = "78.160.32.88",
                            Latitude = 39.933399999999999,
                            Longitude = 32.859699999999997,
                            SavedAt = new DateTime(2026, 6, 16, 14, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
